<?php

/**
 * -------------------------------------------------------------------------
 * TicketFlow plugin for GLPI
 * -------------------------------------------------------------------------
 *
 * MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 * -------------------------------------------------------------------------
 * @copyright Copyright (C) 2026 Felipe Jovino.
 * @license   MIT https://opensource.org/licenses/mit-license.php
 * @link      https://github.com/Jovinull/ticketclock
 * -------------------------------------------------------------------------
 */

declare(strict_types=1);

namespace GlpiPlugin\Ticketclock\Enum;

/**
 * Interactions that push the clock forward.
 *
 * This is the heart of the "who was supposed to answer?" question: an interaction only
 * counts when it comes from the actor the rule is waiting for. Authors are resolved from
 * the ticket actor tables (CommonITILActor types), never from names or free text.
 *
 * Followups generated by TicketFlow itself are excluded from every one of these, so a
 * rule can never reset its own clock.
 */
enum ResetEvent: string
{
    /** A followup written by a requester of the ticket (or by a member of a requester group). */
    case RequesterFollowup = 'requester_followup';

    /** A followup written by an assigned technician (or by a member of an assigned group). */
    case AssigneeFollowup = 'assignee_followup';

    /** Any human followup, whoever wrote it. */
    case AnyFollowup = 'any_followup';

    /** A solution was added to the ticket. */
    case SolutionAdded = 'solution_added';

    /** An approval request attached to the ticket received an answer. */
    case ValidationAnswered = 'validation_answered';

    public function label(): string
    {
        return match ($this) {
            self::RequesterFollowup  => __('Answer from a requester', 'ticketclock'),
            self::AssigneeFollowup   => __('Answer from an assignee', 'ticketclock'),
            self::AnyFollowup        => __('Any followup', 'ticketclock'),
            self::SolutionAdded      => __('Solution added', 'ticketclock'),
            self::ValidationAnswered => __('Approval answered', 'ticketclock'),
        };
    }

    /**
     * @return array<string, string> value => translated label
     */
    public static function options(): array
    {
        $out = [];
        foreach (self::cases() as $case) {
            $out[$case->value] = $case->label();
        }

        return $out;
    }

    /**
     * Decode the persisted representation (a comma separated list).
     *
     * @return list<self>
     */
    public static function decodeList(?string $raw): array
    {
        if ($raw === null || trim($raw) === '') {
            return [];
        }

        $out = [];
        foreach (explode(',', $raw) as $token) {
            $case = self::tryFrom(trim($token));
            if ($case !== null && !in_array($case, $out, true)) {
                $out[] = $case;
            }
        }

        return $out;
    }

    /**
     * @param iterable<self|string> $events
     */
    public static function encodeList(iterable $events): string
    {
        $out = [];
        foreach ($events as $event) {
            $case = $event instanceof self ? $event : self::tryFrom((string) $event);
            if ($case !== null && !in_array($case->value, $out, true)) {
                $out[] = $case->value;
            }
        }

        return implode(',', $out);
    }
}
